/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void userGreeting() {
        App.greetingInGame();
        final String expected = "Welcome to the Brain Games!";
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        App.greetingInGame();
        final var actual = out.toString().trim();

        assertThat(actual).isEqualTo(expected);
    }
}
