/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;


import java.util.Scanner;

import hexlet.code.games.Calc;
import hexlet.code.games.Even;
import hexlet.code.games.GCD;
import hexlet.code.games.Prime;
import hexlet.code.games.Progression;

public class App {
    private static final int EXIT_IDX = 0;
    private static final int GREETING_IDX = 1;
    private static final int EVEN_IDX = 2;
    private static final int CALC_IDX = 3;
    private static final int GCD_IDX = 4;
    private static final int PROGRESSION_IDX = 5;
    private static final int PRIME_IDX = 6;

    private static Scanner scanner = new Scanner(System.in);
    private static int gameNumber;
    private static String[] games = {
        "Exit", "Greet", "Even", "Calc", "GCD", "Progression", "Prime"
    };

    public static void main(String[] args) {

        System.out.println("Please enter the game number and press Enter.");
        for (int i = 0; i < games.length; i += 1) {
            if (EXIT_IDX == i) {
                continue;
            }
            System.out.println(i + " - " + games[i]);
        }
        System.out.println(EXIT_IDX + " - " + games[EXIT_IDX]);

        System.out.print("Your choice: ");
        gameNumber = scanner.nextShort();
        System.out.println();

        if (gameNumber == EXIT_IDX) {
            return;
        }

        Engine.greetingInGame();
        String userName = Cli.promptUserName();
        Engine.greetingUser(userName);

        if (gameNumber == GREETING_IDX) {
            return;
        }

        Engine.setUserName(userName);

        switch (gameNumber) {
            case EVEN_IDX:
                Engine.launchGame(new Even());
                break;
            case CALC_IDX:
                Engine.launchGame(new Calc());
                break;
            case GCD_IDX:
                Engine.launchGame(new GCD());
                break;
            case PROGRESSION_IDX:
                Engine.launchGame(new Progression());
                break;
            case PRIME_IDX:
                Engine.launchGame(new Prime());
                break;
            default:
                System.out.println("There is no such game");
        }
    }
}
